; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                = 10191107-x86_64 MS Windows        
[ DataSettings ]
datatype                           = snProtein                         
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
Labelled Sites                     = All Sites                         
Labels to Include                  =                                   
[ ProcessTypes ]
ppInfer                            = true                              
ppUPGMA                            = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = UPGMA                             
Phylogeny Test                     = ====================              
Test of Phylogeny                  = None                              
No. of Bootstrap Replications      = Not Applicable                    
Substitution Model                 = ====================              
Substitutions Type                 = Amino acid                        
Model/Method                       = Jones-Taylor-Thornton (JTT) model 
Rates and Patterns                 = ====================              
Rates among Sites                  = Uniform Rates                     
Gamma Parameter                    = Not Applicable                    
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Pairwise deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
System Resource Usage              = ====================              
Number of Threads                  = 1                                 
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
