; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                = 10191107-x86_64 MS Windows        
[ DataSettings ]
datatype                           = snProtein                         
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
Labelled Sites                     = All Sites                         
Labels to Include                  =                                   
[ ProcessTypes ]
ppInfer                            = true                              
ppME                               = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = Minimum Evolution method          
Phylogeny Test                     = ====================              
Test of Phylogeny                  = Bootstrap method                  
No. of Bootstrap Replications      = 100                               
Substitution Model                 = ====================              
Substitutions Type                 = Amino acid                        
Model/Method                       = Jones-Taylor-Thornton (JTT) model 
Rates and Patterns                 = ====================              
Rates among Sites                  = Gamma Distributed (G)             
Gamma Parameter                    = 6.00                              
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Partial deletion                  
Site Coverage Cutoff (%)           = 90                                
Tree Inference Options             = ====================              
ME Heuristic Method                = Close-Neighbor-Interchange (CNI)  
Initial Tree for ME                = Obtain initial tree by Neighbor-Joining
ME Search Level                    = 2                                 
System Resource Usage              = ====================              
Number of Threads                  = 8                                 
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
